### ISSUE TITLE
Can't find your SCALE13x talk on any of the schedules

### ISSUE THREAD

**Issue by tamsky** [tamsky/homedir#1]
@justinmayer :

http://www.socallinuxexpo.org/scale/13x/presentations/staying-top-linux-system-security
shows: Wednesday, December 10, 2014 - 16:45

If you know when it is, I'd be happy to hear back.

**Comment by justinmayer** [comment]
That lightning talk is scheduled for 11:45AM on Friday, February, 20th, 2015 in the La Jolla room. Hope to see you there!

Best,

Justin

**Comment by tamsky** [comment]
Thanks!
