### ISSUE TITLE
Howdy, opensource question

### ISSUE THREAD

**Issue by tamsky** [tamsky/homedir#5]
@jameshill

curious if theconversation has published (or has any plans to publish) your internal CMS system that is mentioned in your [2016 Stakeholder report](https://tcusreport2016.theconversation.com/)

Thanks!

**Comment by jameshill** [comment]
Hi Marc,
Apologies for the delay.
No, none of the core CMS platform is open sourced.
​Thank-you for the interest though.

**Comment by tamsky** [comment]
Thank you for your reply.
No worries -- I'll sit tight with the hope that someday that CMS platform will be shared.
